version: '3.8'

services:
  summarizer-api:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    # تحديد الموارد لضمان عدم توقف الجهاز (اختياري)
    deploy:
      resources:
        limits:
          memory: 4G
    environment:
      - PYTHONUNBUFFERED=1